name: db1000n
selector:
  app.kubernetes.io/part-of: db1000n
  app.kubernetes.io/component: api
image: ghcr.io/arriven/db1000n-advanced:latest
resources:
  requests:
    memory: "512Mi"
    cpu: "5000m"
  limits:
    memory: "512Mi"
    cpu: "500m"
securityContext:
  runAsUser: 1000
  runAsGroup: 2000
  fsGroup: 3000

